[package]
name = "rustbot"
version = "0.1.0"
authors = ["NicEastvillage <nicoesterby@gmail.com>"]
edition = "2018"

[dependencies]
rlbot = "0.5.0"
flatbuffers = "0.6.1"
na = { version = "0.18.0", package = "nalgebra" }